name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Test & Build Binary
        shell: bash
        working-directory: ${{ github.action_path }}
        run: |
          test -s bun.lock || bun install --lockfile-only
          bun install --production --frozen-lockfile
          bun run ci
          mkdir -p bin
          bun build --compile --outfile bin/no-response-bin ./src/main.ts
          chmod a+rx bin/no-response-bin
      
